import React, { useEffect, useState } from 'react';
import {
  BarChart3,
  Clock,
  Target,
  Lightbulb,
  CheckCircle,
  Loader2
} from 'lucide-react';
import { PlayerApi } from '../services/playerApi';
import type {
  PlayerStatistics,
  RecommendationData
} from '../types/sudoku';
import { MLInsightsCard } from '../components/MLInsightsCard';

export const StatisticsPage: React.FC = () => {
  const [stats, setStats] = useState<PlayerStatistics | null>(null);
  const [recommendation, setRecommendation] = useState<RecommendationData | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      PlayerApi.getMyStatistics(),
      PlayerApi.getMyRecommendations()
    ])
      .then(([s, r]) => {
        setStats(s);
        setRecommendation(r);
      })
      .catch((err) => console.error('Error fetching statistics:', err))
      .finally(() => setIsLoading(false));
  }, []);

  const formatSeconds = (sec: number) => {
    if (!sec || sec <= 0) return '0:00';
    const m = Math.floor(sec / 60);
    const s = sec % 60;
    return `${m}:${s < 10 ? '0' : ''}${s}`;
  };

  if (isLoading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8 text-cyan-300">
        <Loader2 className="w-8 h-8 animate-spin mb-2" />
        <p className="text-xs font-mono">Aggregating telemetry features...</p>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8 space-y-6">
      {/* Header */}
      <div className="border-b border-slate-800 pb-5">
        <h1 className="text-2xl font-black text-white flex items-center gap-2.5">
          <BarChart3 className="text-cyan-400" />
          <span>Player Performance & Telemetry Analysis</span>
        </h1>
        <p className="text-xs text-slate-400 mt-1 font-mono">
          Behavioral feature engineering vectors generated by Spring Boot PlayerStatisticsService
        </p>
      </div>

      {/* Top ML Insights */}
      <MLInsightsCard recommendation={recommendation} />

      {/* Detailed Behavioral Vectors */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Speed / Pacing */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 backdrop-blur">
          <div className="flex items-center gap-2 text-cyan-400 mb-2">
            <Clock size={16} />
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200">Solving Speed</h3>
          </div>
          <div className="space-y-2 text-xs">
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Average Duration</span>
              <span className="font-mono text-purple-300 font-bold">{formatSeconds(stats?.averageTime || 0)}</span>
            </div>
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Best Duration</span>
              <span className="font-mono text-emerald-300 font-bold">{formatSeconds(stats?.bestTime || 0)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Pacing (Moves / Min)</span>
              <span className="font-mono text-cyan-300 font-bold">{stats?.averageMovesPerMinute || 0}</span>
            </div>
          </div>
        </div>

        {/* Accuracy & Errors */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 backdrop-blur">
          <div className="flex items-center gap-2 text-indigo-400 mb-2">
            <Target size={16} />
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200">Accuracy & Errors</h3>
          </div>
          <div className="space-y-2 text-xs">
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Overall Accuracy</span>
              <span className="font-mono text-indigo-300 font-bold">{Math.round((stats?.averageAccuracy || 0) * 100)}%</span>
            </div>
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Recent Accuracy (5 games)</span>
              <span className="font-mono text-cyan-300 font-bold">{Math.round((stats?.recentAccuracy || 0) * 100)}%</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Recent Error Rate</span>
              <span className="font-mono text-rose-300 font-bold">{Math.round((stats?.recentErrorRate || 0) * 100)}%</span>
            </div>
          </div>
        </div>

        {/* Assistance Dependency */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 backdrop-blur">
          <div className="flex items-center gap-2 text-amber-400 mb-2">
            <Lightbulb size={16} />
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200">Assistance Profile</h3>
          </div>
          <div className="space-y-2 text-xs">
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Avg Hints / Game</span>
              <span className="font-mono text-amber-300 font-bold">{stats?.averageHints || 0}</span>
            </div>
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Avg Undos / Game</span>
              <span className="font-mono text-blue-300 font-bold">{stats?.averageUndos || 0}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Avg Mistakes / Game</span>
              <span className="font-mono text-rose-300 font-bold">{stats?.averageMistakes || 0}</span>
            </div>
          </div>
        </div>

        {/* Experience & Completion */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 backdrop-blur">
          <div className="flex items-center gap-2 text-emerald-400 mb-2">
            <CheckCircle size={16} />
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200">Completion Flow</h3>
          </div>
          <div className="space-y-2 text-xs">
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Total Played</span>
              <span className="font-mono text-slate-200 font-bold">{stats?.gamesPlayed || 0}</span>
            </div>
            <div className="flex justify-between border-b border-slate-800/60 pb-1.5">
              <span className="text-slate-400">Total Solved</span>
              <span className="font-mono text-emerald-300 font-bold">{stats?.gamesCompleted || 0}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Solve Success</span>
              <span className="font-mono text-cyan-300 font-bold">{Math.round((stats?.completionRate || 0) * 100)}%</span>
            </div>
          </div>
        </div>
      </div>

      {/* Visual Progress Bars for Difficulty Handling */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 backdrop-blur">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 mb-4">
          Difficulty Mastery Progression
        </h3>
        <div className="space-y-4">
          <div>
            <div className="flex justify-between text-xs mb-1">
              <span className="font-bold text-emerald-300">Easy Missions Mastery</span>
              <span className="font-mono text-slate-300">{Math.round((stats?.easyCompletionRate || 0) * 100)}% completed</span>
            </div>
            <div className="w-full h-2.5 bg-slate-800 rounded-full overflow-hidden">
              <div
                className="h-full bg-emerald-400 rounded-full transition-all duration-500"
                style={{ width: `${Math.round((stats?.easyCompletionRate || 0) * 100)}%` }}
              ></div>
            </div>
          </div>

          <div>
            <div className="flex justify-between text-xs mb-1">
              <span className="font-bold text-amber-300">Medium Missions Mastery</span>
              <span className="font-mono text-slate-300">{Math.round((stats?.mediumCompletionRate || 0) * 100)}% completed</span>
            </div>
            <div className="w-full h-2.5 bg-slate-800 rounded-full overflow-hidden">
              <div
                className="h-full bg-amber-400 rounded-full transition-all duration-500"
                style={{ width: `${Math.round((stats?.mediumCompletionRate || 0) * 100)}%` }}
              ></div>
            </div>
          </div>

          <div>
            <div className="flex justify-between text-xs mb-1">
              <span className="font-bold text-rose-300">Hard Missions Mastery</span>
              <span className="font-mono text-slate-300">{Math.round((stats?.hardCompletionRate || 0) * 100)}% completed</span>
            </div>
            <div className="w-full h-2.5 bg-slate-800 rounded-full overflow-hidden">
              <div
                className="h-full bg-rose-400 rounded-full transition-all duration-500"
                style={{ width: `${Math.round((stats?.hardCompletionRate || 0) * 100)}%` }}
              ></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
